export enum ActionTypeKeys {
    // location
    UPDATED_LOCATION = "UPDATED_LOCATION",

    // auto sugesstion
    FETCH_SUGGESTIONS_REQUESTED = "FETCH_SUGGESTIONS_REQUESTED",
    FETCH_SUGGESTIONS_FINISHED = "FETCH_SUGGESTIONS_FINISHED",
    FETCH_SUGGESTIONS_FAILED = "FETCH_SUGGESTIONS_FAILED",
    CLEAR_SUGGESTIONS = "CLEAR_SUGGESTIONS",

    // location weathers
    FETCH_LOCATION_WEATHERS_REQUESTED = "FETCH_LOCATION_WEATHERS_REQUESTED",
    FETCH_LOCATION_WEATHERS_FINISHED = "FETCH_LOCATION_WEATHERS_FINISHED",
    FETCH_LOCATION_WEATHERS_FAILED = "FETCH_LOCATION_WEATHERS_FAILED",
}
